---
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present
    tags: mygit
  - name: install tree
    apt:
      nme: tree
      state: present
    tags: mytree
    ignore_errors: yes
  - name: mywget
    apt:
      name: wget
      state: present
    tags: mywget