---
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
<<<<<<< HEAD
  handlers:    
=======
  handlers:
>>>>>>> 5de5aa3577929a42c4a31ea9566ee2e09b2879a1
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
  - name: i want to copy static file into ansible node
    template:
      src: myfile.html
      dest: /var/www/html/index.html
<<<<<<< HEAD
    notify: restartwebserver
=======
    notify: restartwebserver
>>>>>>> 5de5aa3577929a42c4a31ea9566ee2e09b2879a1
