---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      state: present

  - name: i want to start apache2
    service:
      name: apache2
      state: restarted

  - name: i want to install webserver on RadHat nodes
    yum:
      name: httpd
      state: present

  - name: i want to start webserver
    service:
      name: httpd
      state: started