---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="debian"

  - name: i want to start apache2
    service:
      name: apache2
      state:  restarted
    when: ansible_os_family=="debian"

  - name: i want to install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="redhat"

  - name: i want to start httpd
    service:
      name: httpd
      state: restarted
    when: ansible_os_family=="redhat"