---
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myresult
  - name: i want to display first task result
    debug:
      mag: "{{myresult}}"
  - name: i want to install git
    apt:
      name: git
      state: present
    when: myresult.stderr ==""

  - name: i want to inatall tree
    apt:
      name: tree
      state: present
    when: myresult.stderr !=""