---
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
    
  - name: i want to install apache2
    apt:
      name: apache2
      state: present

  - name: i want to start apache2
    service:
      name: apache2
      state: restarted

  - name: i want to copy dynamic file into ansible node servers
    template:
      src: myindex.j2
      dest: /var/www/html/index.html