--- 
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: i want to download file from internet
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/ubuntu/
      force_basic_auth: yes