---
- hosts: 172.31.5.68
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
    
  - name: i want to copy static file into ansible node server
    template:
      src: mystaticfile.html
      dest: /var/www/html/index.html